from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
import uuid
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from app.db import get_db
from app.models import ComplianceCase
from app.schemas import ComplianceStatus, ComplianceSubmission

router = APIRouter(prefix="/compliance", tags=["compliance"])


def generate_case_certificate(case: ComplianceCase) -> str:
    """Generate a PDF certificate for a compliance case and return the file path."""
    output_dir = Path("/tmp/compliance-certificates")
    output_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = output_dir / f"{case.case_id}.pdf"

    c = canvas.Canvas(str(pdf_path), pagesize=letter)
    c.setTitle(f"Compliance Certificate - {case.company_name}")
    c.setFont("Helvetica-Bold", 18)
    c.drawString(72, 750, "Enterprise Compliance Clearance Certificate")

    c.setFont("Helvetica", 12)
    c.drawString(72, 720, f"Company: {case.company_name}")
    c.drawString(72, 700, f"KRA PIN: {case.kra_pin}")
    c.drawString(72, 680, f"Director: {case.director_name}")
    c.drawString(72, 660, f"Risk Level: {case.risk_level}")
    c.drawString(72, 640, f"Status: {case.status}")
    c.drawString(72, 620, f"KYB Score: {int(case.kyb_score)}%")
    c.drawString(72, 600, f"KYC Score: {int(case.kyc_score)}%")
    c.drawString(72, 580, f"AML Score: {int(case.aml_score)}%")
    c.drawString(72, 560, f"Clearance: {case.clearance}")

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(72, 120, "This document is a sample compliance deliverable for the white-label audit workflow.")
    c.drawString(72, 100, "Generated by the Enterprise KYB / KYC / AML Compliance Engine.")
    c.save()

    return str(pdf_path)


@router.get("/cases")
def list_cases(db: Session = Depends(get_db)) -> list[dict]:
    """List all compliance cases."""
    cases = db.query(ComplianceCase).order_by(ComplianceCase.created_at.desc()).all()
    return [
        {
            "id": case.case_id,
            "company_name": case.company_name,
            "kra_pin": case.kra_pin,
            "status": case.status,
            "kyb_score": int(case.kyb_score),
            "kyc_score": int(case.kyc_score),
            "aml_score": int(case.aml_score),
            "clearance": case.clearance,
        }
        for case in cases
    ]


@router.post("/submit")
def submit_case(payload: ComplianceSubmission, db: Session = Depends(get_db)) -> dict:
    """Submit a new compliance case."""
    case_id = str(uuid.uuid4())[:8]

    new_case = ComplianceCase(
        case_id=f"case-{case_id}",
        company_name=payload.company_name,
        kra_pin=payload.kra_pin,
        director_name=payload.director_name,
        document_type=payload.document_type,
        risk_level=payload.risk_level,
        status="submitted",
        kyb_score=88,
        kyc_score=84,
        aml_score=90,
        clearance="pending",
    )

    db.add(new_case)
    db.commit()
    db.refresh(new_case)

    return {
        "id": new_case.case_id,
        "company_name": new_case.company_name,
        "kra_pin": new_case.kra_pin,
        "director_name": new_case.director_name,
        "document_type": new_case.document_type,
        "risk_level": new_case.risk_level,
        "status": new_case.status,
        "message": "Compliance intake created successfully.",
    }


@router.get("/status/{case_id}")
def get_case_status(case_id: str, db: Session = Depends(get_db)) -> ComplianceStatus:
    """Get detailed status of a specific compliance case."""
    case = db.query(ComplianceCase).filter(ComplianceCase.case_id == case_id).first()

    if not case:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found")

    return ComplianceStatus(
        id=case.case_id,
        company_name=case.company_name,
        kra_pin=case.kra_pin,
        status=case.status,
        kyb_score=int(case.kyb_score),
        kyc_score=int(case.kyc_score),
        aml_score=int(case.aml_score),
        clearance=case.clearance,
    )


@router.post("/certificate/{case_id}")
def generate_certificate(case_id: str, db: Session = Depends(get_db)) -> dict:
    """Generate a PDF-based compliance clearance certificate for a case."""
    case = db.query(ComplianceCase).filter(ComplianceCase.case_id == case_id).first()
    if not case:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found")

    pdf_path = generate_case_certificate(case)
    return {
        "case_id": case.case_id,
        "company_name": case.company_name,
        "pdf_path": pdf_path,
        "status": "certificate_generated",
        "message": "Compliance certificate generated successfully.",
    }
